Второе домашнее задание
orehusLina/headsNhands pull request #2
Opened 2023-10-26 00:06 UTC by orehusLina

Не очень получилось сделать кнопку из 2b, точнее сам drawable получился, я устанавливаю его бэкграундом на кнопке, по завету александра климова и стаковерфлоу этого должно быть достаточно, но этого не достаточно: стиль drawable с закругленными краями корректно работает, а цвет перекрывает...

Еще был вариант сделать это ImageButton и привязать к ней текст каким-нибудь FrameLayout, но выглядело довольно костыльно, я не знаю, почему мое не работает. 

Еще я случайно закрыла старый пулреквест... Но я в этом поправила проверку на пустые поля + убрала сеттеры из класса, с некрасивыми переменными

2023-10-26 09:34 UTC, DmitriyTSt requested changes
кроме 9 patch ковра, еще лишние есть, много

2023-10-26 09:34 UTC, DmitriyTSt commented on Lesson2_Orekhova/app/src/main/res/values-ru/colors.xml
> +    <color name="black">#FF000000</color>
зачем этот файл ? он ничего не меняет

2023-10-26 09:34 UTC, DmitriyTSt commented on Lesson2_Orekhova/app/src/main/res/values-sw325dp/colors.xml
> +    <color name="black">#FF000000</color>
не обязательно повторять ресурсы в других конфигурациях если они не меняются от дефолта

2023-10-26 09:34 UTC, DmitriyTSt commented on Lesson2_Orekhova/app/src/main/res/values-sw325dp/colors.xml
> +    <color name="pushkinColor">@color/black</color>
все ресурсы кроме атрибутов и стилей snake_case

2023-10-26 09:34 UTC, DmitriyTSt commented on Lesson2_Orekhova/app/src/main/res/values-v23/strings.xml
> +    <string name="buttonAndroidVersion">Радость и счастье</string>
и тут тоже, видишь строка автоматическая которая через _

2023-10-26 09:34 UTC, DmitriyTSt commented on Lesson2_Orekhova/app/src/main/res/values-v23/strings.xml
> +    <string name="app_name">Lesson2_Orekhova</string>
и тут опять не обязательно если не меняется переназначать

2023-10-26 09:34 UTC, DmitriyTSt commented on Lesson2_Orekhova/app/src/main/res/values-ru/themes.xml
> +    <style name="Base.Theme.Lesson2_Orekhova" parent="Theme.Material3.DayNight.NoActionBar">
тема в другой конфигурации которая не нужна, тут нчиего нет

2023-10-26 09:36 UTC, DmitriyTSt commented
цвет кнопки - app:backgroundTint можно поменять

2023-10-26 10:30 UTC, orehusLina commented
> цвет кнопки - app:backgroundTint можно поменять

Спасибо, все поправила)

2023-10-30 05:29 UTC, DmitriyTSt approved these changes

2023-10-30 10:20 UTC, merged